// Optional: requires Playwright and Chromium. Start server first.
const {chromium}=require('playwright');const fs=require('node:fs');const path=require('node:path');const output=path.resolve('test-artifacts');fs.mkdirSync(output,{recursive:true});const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:8000');await page.waitForTimeout(450);
await page.locator('[data-section="incomes"]').selectOption('yes');await page.locator('[data-add="incomes"]').click();const input=page.locator('[data-bind="incomes.0.amount"]');await input.fill('1,250,000.50');await input.blur();assert.equal(await input.inputValue(),'1,250,000.50');await input.focus();assert.equal(await input.inputValue(),'1250000.50');await input.blur();await page.waitForTimeout(450);assert.equal(await page.locator('#save-status').textContent(),'บันทึกแล้ว');
await page.reload();await page.waitForTimeout(100);assert.equal(await page.locator('[data-bind="incomes.0.amount"]').inputValue(),'1,250,000.50');await page.locator('[data-section="incomes"]').selectOption('no');assert.equal(await page.locator('[data-bind="incomes.0.amount"]').count(),1);
await page.locator('[data-unknown="incomes.0.amount"]').click();assert.match(await page.locator('#finance-results').innerText(),/ยังไม่แสดงผลรวม/);await page.waitForTimeout(450);await page.reload();assert.equal(await page.locator('[data-bind="incomes.0.amount"]').inputValue(),'');
page.once('dialog',d=>d.dismiss());await page.locator('[data-action="clear-storage"]').click();assert.equal(await page.locator('[data-bind="incomes.0.amount"]').count(),1);
page.once('dialog',d=>d.accept());await page.locator('[data-action="clear-storage"]').click();assert.equal(await page.evaluate(()=>localStorage.getItem('fp.plan.v2.3')),null);assert.equal(await page.locator('[data-bind="incomes.0.amount"]').count(),0);
await page.evaluate(()=>localStorage.setItem('fp.plan.v2.3','broken'));await page.reload();assert.match(await page.locator('#storage-warning').innerText(),/ระงับ/);await page.locator('[data-bind="profile.name"]').fill('test');await page.waitForTimeout(500);assert.equal(await page.evaluate(()=>localStorage.getItem('fp.plan.v2.3')),'broken');
page.once('dialog',d=>d.accept());await page.locator('[data-action="clear-storage"]').click();await page.locator('[data-action="demo"]').click();await page.waitForTimeout(450);
for(const width of [1440,390]){await page.setViewportSize({width,height:1000});for(const p of ['finance','protection','goals','retirement','tax','report']){await page.locator('nav a[href="#'+p+'"]').click();await page.waitForTimeout(50);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),p+' overflow '+width);if(width===390)assert.ok(await page.locator('.form-grid').evaluateAll(els=>els.every(el=>getComputedStyle(el).gridTemplateColumns.trim().split(/\s+/).length===1)));await page.screenshot({path:path.join(output,p+'-'+width+'.png'),fullPage:true})}}
assert.deepEqual(errors,[]);console.log('PASS browser: money focus/blur, reload, preserve existing, unknown, clear cancel/confirm, corrupt lock, 6 pages × desktop/mobile no overflow/single column, no JS errors');await browser.close()})().catch(e=>{console.error(e);process.exit(1)});
