const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,args:['--no-sandbox']});try{
const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:8000');await page.locator('#focus-choices').waitFor();
assert.equal(await page.locator('#nav').isVisible(),false);assert.equal(await page.locator('[data-bind="profile.focus"]').count(),0);assert.equal(await page.locator('#sim-saving').count(),0);
await page.locator('[data-bind="profile.name"]').fill('ทดสอบกรอกง่าย');await page.locator('[data-bind="profile.age"]').fill('36');await page.locator('[data-bind="profile.occupation"]').selectOption('freelance');await page.locator('[data-plan-action="next"]').click();
await page.locator('[data-section="incomes"]').waitFor();assert.equal(await page.locator('[data-section="pvd"]').isVisible(),false);
await page.locator('[data-section="incomes"]').selectOption('yes');await page.locator('[data-add="incomes"]').click();await page.locator('[data-bind="incomes.0.amountMode"]').selectOption('net');await page.locator('[data-bind="incomes.0.amount"]').fill('50000');await page.locator('[data-bind="incomes.0.amount"]').blur();
assert.equal(await page.locator('[data-bind="incomes.0.taxDeduct"]').isVisible(),false);await page.locator('[data-plan-action="next"]').click();
for(const k of ['expenses','debts','policies'])assert.equal(await page.locator(`[data-section="${k}"]`).isVisible(),true);
await page.locator('[data-plan-action="skip"]').click();for(const k of ['assets','portfolios','pvd','goals']){assert.equal(await page.locator(`[data-section="${k}"]`).isVisible(),true);await page.locator(`[data-section="${k}"]`).selectOption('no');}
await page.locator('[data-plan-action="next"]').click();await page.locator('.pending-steps').waitFor();assert.deepEqual(await page.evaluate(()=>window.catnayPlan.get().review.planner.deferred),['expense']);
await page.reload();await page.locator('.pending-steps [data-flow-step="2"]').click();await page.locator('[data-section="expenses"]').waitFor();await page.locator('[data-section="expenses"]').selectOption('no');await page.locator('[data-section="debts"]').selectOption('no');await page.locator('[data-section="policies"]').selectOption('no');await page.locator('[data-plan-action="next"]').click();await page.locator('[data-plan-action="next"]').click();await page.locator('[data-open-topic="retirement"]').waitFor();assert.equal(await page.locator('.pending-steps').count(),0);
await page.locator('[data-open-topic="retirement"]').click();await page.locator('[data-bind="retirement.expense"]').waitFor();await page.locator('#planner-shell [data-plan-action="overview"]').click();await page.locator('[data-open-topic="retirement"]').waitFor();assert.equal(await page.evaluate(()=>window.catnayPlan.get().incomes[0].amount),50000);
for(const width of [390,1440]){await page.setViewportSize({width,height:900});for(let i=0;i<5;i++){await page.locator(`#planner-shell [data-flow-step="${i}"]`).click();await page.waitForTimeout(80);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'overflow '+width+' step '+i);await page.screenshot({path:`test-artifacts/friendly-${width}-${i}.png`,fullPage:false});}}
assert.deepEqual(errors,[]);console.log('PASS friendly flow: 5 steps, contextual fields, persisted deferrals, direct editing, optional planning, responsive screens');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
