const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,args:['--no-sandbox']});try{
 const page=await browser.newPage({viewport:{width:390,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:8000');await page.locator('[data-quick-topic="tax"]').waitFor();
 for(let i=0;i<5;i++){await page.locator(`#planner-shell [data-flow-step="${i}"]`).click();await page.locator('.quick-plans').waitFor();assert.equal(await page.locator('.quick-plans button:visible').count(),4);}
 await page.locator('#planner-shell [data-flow-step="1"]').click();await page.locator('[data-preset="salary"]').click();const amount=page.locator('[data-bind="incomes.0.amount"]');assert.equal(await amount.inputValue(),'');await amount.fill('45000');await amount.blur();
 await page.locator('[data-quick-topic="tax"]').click();await page.waitForFunction(()=>location.hash==='#tax');await page.reload();await page.locator('[data-quick-topic="retirement"]').click();await page.waitForFunction(()=>location.hash==='#retirement');await page.locator('#planner-shell [data-plan-action="return-origin"]').click();await amount.waitFor();assert.equal(Number((await amount.inputValue()).replaceAll(',','')),45000);assert.equal(await page.locator('#planner-shell [aria-current="step"]').getAttribute('data-flow-step'),'1');
 await page.locator('[data-preset="salary"]').click();assert.equal(await page.evaluate(()=>window.catnayPlan.get().incomes.length),1);assert.equal(Number((await amount.inputValue()).replaceAll(',','')),45000);
 await page.locator('[data-preset="commission"]').click();assert.equal(await page.locator('[data-bind="incomes.1.amount"]').inputValue(),'');
 await page.locator('#planner-shell [data-flow-step="2"]').click();await page.locator('[data-preset="food"]').click();await page.locator('[data-bind="expenses.0.amount"]').fill('8000');await page.locator('[data-preset="home"]').click();assert.equal(await page.evaluate(()=>window.catnayPlan.get().expenses.length),1);assert.equal(await page.locator('[data-bind="debts.0.balance"]').inputValue(),'');
 await page.locator('#planner-shell [data-flow-step="4"]').click();await page.locator('#overview-metrics').waitFor();assert.match(await page.locator('#overview-metrics').innerText(),/รอข้อมูล/);
 const fix=page.locator('[data-fix-step="1"]').filter({hasText:'ค่านายหน้า'});await fix.click();await page.locator('[data-bind="incomes.1.amount"]').waitFor();assert.equal(await page.evaluate(()=>document.activeElement.dataset.bind),'incomes.1.amount');
 await page.evaluate(async()=>{const {demo}=await import('./model.mjs?v=2.6-flow2');window.catnayPlan.replace(demo());});await page.locator('#planner-shell [data-flow-step="4"]').click();await page.locator('#priority-actions').waitFor();const text=await page.locator('#overview-metrics').innerText();for(const label of ['เงินเหลือเฉลี่ยหลังออม','เงินสำรองครอบคลุม','ค่างวดหนี้ต่อเดือน'])assert.ok(text.includes(label));assert.ok(await page.locator('#priority-actions .suggestion').count()<=3);
 for(const width of [390,1440]){await page.setViewportSize({width,height:1000});for(const route of ['report','tax']){if(route==='tax')await page.locator('[data-quick-topic="tax"]').click();else await page.locator('#planner-shell [data-flow-step="4"]').click();await page.waitForTimeout(100);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:`test-artifacts/ux2-${route}-${width}.png`});}}
 assert.deepEqual(errors,[]);console.log('PASS UX actions: shortcuts at every step, return across reload/topics, presets without invented amounts or duplicates, precise missing-field links and prioritized overview');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
