const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,args:['--no-sandbox']});try{const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:8000');await page.locator('[data-action="demo"]').click();
assert.equal(await page.evaluate(()=>window.catnayPlan.get().profile.example),true);
for(const route of ['finance','protection','goals','retirement','tax','report']){await page.locator(`nav a[href="#${route}"]`).click();assert.equal(await page.locator('#completion-label').textContent(),'กรอกครบ');assert.ok(!(await page.locator(`#${route}-results`).innerText()).includes('ผลยังไม่พร้อม'));}
await page.locator('nav a[href="#retirement"]').click();assert.match(await page.locator('#retirement-results').innerText(),/92,697/);assert.match(await page.locator('#retirement-results').innerText(),/ต่ำ/);
// Unknown solar amount must not hide finance or retirement.
await page.locator('nav a[href="#tax"]').click();await page.locator('[data-unknown="tax.solar"]').evaluate(el=>{for(let p=el.parentElement;p;p=p.parentElement)if(p.tagName==='DETAILS')p.open=true;});await page.locator('[data-unknown="tax.solar"]').click();assert.match(await page.locator('#tax-results').innerText(),/ยังไม่แสดงผลรวม/);await page.locator('nav a[href="#finance"]').click();assert.match(await page.locator('#finance-results').innerText(),/สินทรัพย์สุทธิ/);
// Reload complete example; must require confirmation even after automatic save.
let prompted=false;page.once('dialog',async d=>{prompted=true;await d.accept();});await page.locator('[data-action="demo"]').click();assert.equal(prompted,true);
// Salary certificate includes its two linked bonuses: suppress only their tax figures.
await page.locator('[data-bind="incomes.0.taxSource"]').evaluate(el=>{for(let p=el.parentElement;p;p=p.parentElement)if(p.tagName==='DETAILS')p.open=true;});await page.locator('[data-bind="incomes.0.taxSource"]').selectOption('manual');await page.locator('[data-bind="incomes.0.gross"]').fill('1200000');await page.locator('[data-bind="incomes.0.withheld"]').fill('90000');await page.locator('[data-bind="incomes.0.certificateIncludesBonus"]').check();await page.locator('nav a[href="#tax"]').click();assert.match(await page.locator('#tax-results').innerText(),/1,200,000/);assert.match(await page.locator('#tax-results').innerText(),/90,000/);
await page.reload();assert.equal(await page.evaluate(()=>window.catnayPlan.get().incomes[0].certificateIncludesBonus),true);
// Tax-year facts, not current marital status alone, control eligibility.
await page.locator('[data-bind="tax.spouseIncome"]').selectOption('yes');assert.match(await page.locator('#tax-results').innerText(),/ยืนยันเงื่อนไขคู่สมรส/);
page.once('dialog',d=>d.accept());await page.locator('[data-action="demo"]').click();
for(const width of [1440,390]){await page.setViewportSize({width,height:1000});for(const route of ['finance','retirement','report']){await page.locator(`nav a[href="#${route}"]`).click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),route+' overflow');await page.screenshot({path:`test-artifacts/v25-${route}-${width}.png`,fullPage:false});}}
await page.emulateMedia({media:'print'});await page.pdf({path:'test-artifacts/v25-example-report.pdf',format:'A4',printBackground:true});assert.deepEqual(errors,[]);console.log('PASS V2.5 browser: complete example, 50k retirement, certificate bonus deduplication, scoped unknown, persistence, replacement confirmation, mobile layouts and print PDF');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
