import assert from 'node:assert/strict';
import {fresh,demo,factories,incomeTax,taxResult,cashflow,retirementResult,retirementScenarios,debtSchedule,esgxCarry,decodePlan,portfolioTax} from '../dist/model.mjs';
import {meta,pack,missing,unknownFor} from '../dist/experience.mjs';
const s=fresh(),salary={...factories.incomes(),id:'salary',amount:80000,amountMode:'gross',taxSource:'estimate',taxDeduct:5000,startMonth:7,endMonth:12};
s.incomes=[salary,{...factories.incomes(),id:'bonus',salaryId:'salary',frequency:'yearly',month:12,amount:120000,amountMode:'gross',taxSource:'estimate',taxDeduct:12000}];
assert.equal(taxResult(s).gross,600000);assert.equal(taxResult(s).withheld,42000);assert.equal(cashflow(s).income,558000);assert.equal(cashflow(s).months[0].income,0);assert.equal(cashflow(s).months[11].income,183000);
s.portfolios=[{...factories.portfolios(),type:'PVD',payroll:true,incomeId:'salary',monthly:4000,taxAuto:true}];assert.equal(portfolioTax(s.portfolios[0],s),24000);assert.equal(cashflow(s).income,534000);
Object.assign(salary,{taxSource:'manual',gross:600000,withheld:42000,certificateIncludesBonus:true});assert.equal(taxResult(s).gross,600000);assert.equal(taxResult(s).withheld,42000);assert.equal(incomeTax(s,s.incomes[1]).coveredBy,'salary');
salary.certificateIncludesBonus=false;salary.gross=480000;salary.withheld=30000;assert.equal(taxResult(s).gross,600000);assert.equal(taxResult(s).withheld,42000);
salary.taxInclude=false;assert.equal(taxResult(s).gross,120000);salary.taxInclude=true;
s.incomes[1].salaryId='removed';salary.certificateIncludesBonus=true;assert.equal(taxResult(s).gross,600000); // orphan bonus cannot silently vanish
const spouse=fresh();spouse.tax.spouse=true;assert.equal(taxResult(spouse).parts.find(x=>x[0]==='คู่สมรสไม่มีเงินได้')[1],0);Object.assign(spouse.tax,{maritalDuringYear:'during',spouseIncome:'none'});assert.equal(taxResult(spouse).parts.find(x=>x[0]==='คู่สมรสไม่มีเงินได้')[1],60000);spouse.tax.spouseLife=10000;assert.equal(taxResult(spouse).parts.find(x=>x[0]==='ประกันชีวิตคู่สมรส')[1],0);spouse.tax.spouseFullYear=true;spouse.tax.maritalDuringYear='all';assert.equal(taxResult(spouse).parts.find(x=>x[0]==='ประกันชีวิตคู่สมรส')[1],10000);spouse.tax.spouseIncome='yes';assert.equal(taxResult(spouse).parts.find(x=>x[0]==='คู่สมรสไม่มีเงินได้')[1],0);
const cal=fresh();cal.policies=[{...factories.policies(),premium:120000,due:'2026-12-01'}];assert.equal(cashflow(cal).months[0].remaining,0);assert.equal(cashflow(cal).months[11].remaining,-120000);assert.equal(cashflow(cal).months[0].averageRemaining,-10000);cal.policies[0].due='';assert.equal(cashflow(cal).months[0].remaining,null);
const debt={...factories.debts(),balance:120000,monthly:10000,method:'reducing',rate:0};assert.equal(debtSchedule(debt).months,12);assert.equal(debtSchedule({...debt,extra:10000}).months,6);assert.equal(debtSchedule({...debt,monthly:100,rate:12}).unpayable,true);assert.equal(debtSchedule({...debt,method:'manual'}).supported,false);
const ltf=fresh();Object.assign(ltf.tax,{esgxMode:'calculate',esgxTransferred:380000,esgxConfirmed:true});assert.equal(esgxCarry(ltf),20000);ltf.tax.esgxTransferred=800000;assert.equal(esgxCarry(ltf),50000);ltf.tax.esgxConfirmed=false;assert.equal(esgxCarry(ltf),0);
const d=demo();for(const page of ['finance','protection','goals','retirement','tax','report'])assert.deepEqual(missing(d,page),[],page);assert.equal(d.retirement.expense,50000);assert.equal(taxResult(d).gross,1200000);assert.equal(taxResult(d).withheld,90000);assert.ok(Math.abs(retirementResult(d).firstExpense-92697.204916)<.01);assert.equal(retirementResult(d).timeline.at(-1).age,89);assert.equal(retirementResult(d).duration,30);const scenarios=retirementScenarios(d);assert.ok(scenarios[0].extraNeeded>scenarios[1].extraNeeded&&scenarios[1].extraNeeded>scenarios[2].extraNeeded);assert.deepEqual(decodePlan(pack(d)),d);
meta(d).unknown['tax.solar']=true;assert.equal(unknownFor(d,'finance'),false);assert.equal(unknownFor(d,'tax'),true);delete d.ux.unknown['tax.solar'];d.ux.unknown['incomes.'+d.incomes[0].id+'.amount']=true;assert.equal(unknownFor(d,'finance'),true);assert.equal(unknownFor(d,'tax'),true);assert.equal(unknownFor(d,'retirement'),false);
const legacy=structuredClone(d);legacy.version=6;for(const r of legacy.incomes)for(const k of ['startMonth','endMonth','salaryId','taxSource','certificateIncludesBonus'])delete r[k];for(const r of legacy.debts)for(const k of ['method','extra'])delete r[k];delete legacy.tax.maritalDuringYear;delete legacy.tax.spouseIncome;const migrated=decodePlan({app:'FP',version:6,data:legacy});assert.equal(migrated.version,7);assert.equal(migrated.incomes[0].taxSource,'manual');assert.equal(migrated.incomes[0].gross,960000);assert.equal(migrated.debts[0].method,'manual');assert.equal(migrated.tax.maritalDuringYear,'none');assert.equal(migrated.ux.reviewed.tax,undefined);assert.equal(legacy.version,6);
const bad=pack(d);bad.data.incomes[0].endMonth=13;assert.throws(()=>decodePlan(bad));
console.log('PASS V2.5: linked bonus/certificate, partial-year payroll/PVD, spouse eligibility, payment calendar, debt payoff, LTF carry, complete demo, retirement scenarios, scoped unknowns, legacy migration');

const scoped=demo();scoped.ux.unknown["policies."+scoped.policies[0].id+".premium"]=true;assert.deepEqual(missing(scoped,"retirement"),[]);scoped.tax.socialAuto=true;scoped.ux.unknown["incomes."+scoped.incomes[0].id+".socialDeduct"]=true;assert.equal(unknownFor(scoped,"tax"),true);
